os:
  - osx

language: java

before_install:
  - brew update
  - npm install --global surge

install:
  - brew cask install google-chrome
  - brew cask install chromedriver
  - brew install gauge
  - gauge install java
  - gauge install html-report

cache:
  directories:
  - $HOME/.m2

script:
  - curl -L https://bintray.com/artifact/download/gauge/activeadmin-demo/activeadmin-demo.war -O
  - nohup java -jar activeadmin-demo.war >/dev/null 2>&1 &
  - sleep 30
  - mvn clean
  - mvn test

deploy:
  provider: surge
  project: ./reports/html-report/
  domain: gauge-java-maven-selenium.surge.sh
  skip_cleanup: true
